#!/bin/bash

set -e
# Since pkg installer can't build with large files (the default model is
# several GB), the model dir is split into multiple 2gb files while building
# the installer; this script joins them back and extracts them in place.

MODELS_DIR="/usr/local/share/tiles/models/huggingface/hub"

cd "${MODELS_DIR}"

cat gemma-4-12b-it-GGUF.tar.gz.part.* > gemma-4-12b-it-GGUF.tar.gz

tar -xzf gemma-4-12b-it-GGUF.tar.gz -C .

rm -f gemma-4-12b-it-GGUF.tar.gz.part.*

rm -f gemma-4-12b-it-GGUF.tar.gz
