from dataclasses import dataclass
from enum import Enum, auto
from typing import Annotated, Any, Dict, List, Literal, Union, override

from openresponses_types import (
    FunctionCallStatus,
    InputFileContentParam,
    InputImageContentParamAutoParam,
    InputTextContentParam,
    InputVideoContent,
    ReasoningParam,
    ToolChoiceValueEnum,
    TruncationEnum,
    Type15,
)
from openresponses_types.types import (
    AssistantMessageItemParam,
    DeveloperMessageItemParam,
    Error,
    FunctionCallItemParam,
    FunctionCallOutputItemParam,
    FunctionToolParam,
    IncompleteDetails,
    ItemReferenceParam,
    ReasoningEffortEnum,
    StreamOptionsParam,
    SystemMessageItemParam,
    ToolChoiceParam,
    UserMessageItemParam,
)
from pydantic import AliasChoices, BaseModel, Field


class CompletionRequest(BaseModel):
    model: str
    prompt: Union[str, List[str]]
    max_tokens: int | None = None
    temperature: float | None = 0.7
    top_p: float | None = 0.9
    stream: bool | None = False
    stop: Union[str, List[str]] | None = None
    repetition_penalty: float | None = 1.1


class ChatMessage(BaseModel):
    role: str = Field(..., pattern="^(system|user|assistant)$")
    content: str


class ChatCompletionRequest(BaseModel):
    model: str
    messages: List[ChatMessage]
    chat_start: bool
    python_code: str
    max_tokens: int | None = None
    temperature: float | None = 0.7
    top_p: float | None = 0.9
    stream: bool | None = False
    stop: Union[str, List[str]] | None = None
    repetition_penalty: float | None = 1.1


class CompletionResponse(BaseModel):
    id: str
    object: str = "text_completion"
    created: int
    model: str
    choices: List[Dict[str, Any]]
    usage: Dict[str, int]


class ChatCompletionResponse(BaseModel):
    id: str
    object: str = "chat.completion"
    created: int
    model: str
    choices: List[Dict[str, Any]]
    # usage: Dict[str, int]


class ModelInfo(BaseModel):
    id: str
    object: str = "model"
    owned_by: str = "mlx-knife"
    permission: List = []
    context_length: int | None = None


class StartRequest(BaseModel):
    model: str
    memory_path: str
    system_prompt: str
    model_cache_path: str


class downloadRequest(BaseModel):
    model: str


class CUserMessageItemParam(UserMessageItemParam):
    type: Literal["message"] = "message"


class CSystemMessageItemParam(SystemMessageItemParam):
    type: Literal["message"] = "message"


class CDeveloperMessageItemParam(DeveloperMessageItemParam):
    type: Literal["message"] = "message"


class CAssistantMessageItemParam(AssistantMessageItemParam):
    type: Literal["message"] = "message"


class CReasoningItemParam(BaseModel):
    id: str | None = None
    type: Literal["reasoning"] = "reasoning"
    summary: list[Dict[str, Any]] = Field(default_factory=list)
    content: Any | None = None
    encrypted_content: str | None = None


class CFunctionTool(BaseModel):
    name: Annotated[str, Field(max_length=64, min_length=1)]
    description: str | None = None
    parameters: dict | None = None
    strict: bool | None = None
    type: Type15


class CFunctionCallItemParam(BaseModel):
    type: Literal["function_call"] = "function_call"
    id: str | None = None
    call_id: Annotated[
        str,
        Field(
            description="The unique ID of the function tool call generated by the model.",
            max_length=64,
            min_length=1,
        ),
    ]
    name: Annotated[
        str,
        Field(
            description="The name of the function to call.",
            max_length=64,
            min_length=1,
        ),
    ]
    arguments: Annotated[
        str, Field(description="The function arguments as a JSON string.")
    ]
    status: FunctionCallStatus | None = None


class CFunctionCallOutputItemParam(BaseModel):
    type: Literal["function_call_output"] = "function_call_output"
    id: str | None = None
    call_id: Annotated[
        str,
        Field(
            description="The unique ID of the function tool call generated by the model.",
            max_length=64,
            min_length=1,
        ),
    ]
    output: Annotated[
        str
        | list[
            Annotated[
                InputTextContentParam
                | InputImageContentParamAutoParam
                | InputFileContentParam
                | InputVideoContent,
                Field(),
            ]
        ],
        Field(description="Text, image, or file output of the function tool call."),
    ]
    status: FunctionCallStatus | None = None


class ResponsesRequest(BaseModel):
    model: str = "mlx-community/gpt-oss-20b-MXFP4-Q4"
    input: (
        str
        | list[
            ItemReferenceParam
            | CReasoningItemParam
            | CUserMessageItemParam
            | CSystemMessageItemParam
            | CDeveloperMessageItemParam
            | CAssistantMessageItemParam
            | CFunctionCallItemParam
            | CFunctionCallOutputItemParam
        ]
    )
    reasoning: ReasoningParam = ReasoningParam(
        effort=ReasoningEffortEnum.low, summary=None
    )
    previous_response_id: str | None = None
    stream: bool | None = False
    stream_options: StreamOptionsParam | None = None
    tools: list[CFunctionTool] | None = None
    tool_choice: ToolChoiceParam | None = ToolChoiceParam(ToolChoiceValueEnum.auto)
    temperature: float | None = 0.7
    top_p: float | None = 1
    max_output_tokens: int | None = None
    store: bool = False
    # other service tiers are default, flex, priority
    service_tier: str = "auto"
    top_logprobs: int = 0
    # can put in the Developer msg if none there
    instructions: str | None = None
    # auto/disabled, returns 400 on disabled
    truncation: TruncationEnum = TruncationEnum.disabled
    prompt_cache: str | None = Field(
        default=None, validation_alias=AliasChoices("prompt_cache", "prompt_cache_key")
    )
    safety_identifier: str | None = None
    max_tool_calls: int | None = None
    background: bool = False


class ResponsesResponse(BaseModel):
    id: str
    object: str = "response"
    created_at: int
    status: str
    completed_at: int | None = None
    error: Error | None = None
    incomplete_details: IncompleteDetails | None = None
    instructions: str | None = None
    max_output_tokens: int | None = None
    model: str
    output: list[Dict[str, Any]]
    parallel_tool_calls: bool = True
    previous_response_id: str = ""
    reasoning: Dict[str, Any] | None = Field(default_factory=dict)
    store: bool = True
    temperature: float = 1.0
    text: Dict[str, Any] = Field(default_factory=lambda: {"format": {"type": "text"}})
    tool_choice: Union[str, Dict[str, Any]] = "auto"
    tools: List[Dict[str, Any]] = Field(default_factory=list)
    top_p: float = 1.0
    truncation: str = "disabled"
    usage: Dict[str, Any]
    user: str | None = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


@dataclass
class GenerationMetrics:
    """Benchmarking metrics for token generation."""

    ttft_ms: float  # Time to first token in milliseconds
    total_tokens: int  # Total tokens generated
    tokens_per_second: float  # Throughput
    total_latency_s: float  # End-to-end latency in seconds


@dataclass
class ToolCallStart:
    name: str


from enum import IntEnum


@dataclass
class ToolCallStart:
    name: str


class OutputIndex(IntEnum):
    MESSAGE = 0
    REASONING = 1


class OutputItemDeltaModel(BaseModel):
    item_name: str
    index: int
    item_id: str
    delta: str
    content_index: int
