[[runtimes]]
name = "cpython3.13"
python_implementation = "cpython@3.13.11"
requirements = []
platforms = [
    "macosx_arm64",
    "linux_x86_64",
]


[[frameworks]]
name = "mlx"
runtime = "cpython3.13"
linux_target = "glibc@2.35"
macosx_target = "14"
requirements = [
    "mlx==0.31.1"
]

[[applications]]
name = "server"
launch_module = "../main.py"
frameworks = ["mlx"]
requirements = [
    "fastapi==0.119.0",
    "uvicorn==0.38.0",
    "mlx-lm==0.31.0",
    "black==25.9.0",
    "openai-harmony==0.0.8",
    "openresponses-types",
    "httpx==0.28.1"
]

[tool.uv]
exclude-newer="2026-04-05T09:43:13.300458+00:00"

# Only resolve for the relevant target platforms
environments = [
    "sys_platform == 'darwin' and platform_machine == 'arm64'",
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
