[[runtimes]]
name = "cpython3.13"
python_implementation = "cpython@3.13.11"
requirements = []
macosx_target = "14"
platforms = [
    "macosx_arm64",
]


[[frameworks]]
name = "mlx"
runtime = "cpython3.13"
macosx_target = "14"
requirements = [
    "mlx==0.31.1"
]

[[applications]]
name = "server"
launch_module = "../../main.py"
frameworks = ["mlx"]
requirements = [
    "fastapi==0.119.0",
    "uvicorn==0.38.0",
    "mlx-lm==0.31.0",
    "openresponses-types",
    "openai-harmony @ https://github.com/tilesprivacy/tiles-harmony/releases/download/v0.0.8-rc.2/openai_harmony-0.0.8rc2-cp38-abi3-macosx_arm64.whl#sha256=43d85451b30c7f4e78e3285fb8e807a7506b0acb939853d4f6b0898e12c044df",
    "httpx==0.28.1",
    ]

[tool.uv]
environments = [
    "sys_platform == 'darwin' and platform_machine == 'arm64'",
]
