[package]
name = "tiles"
version = "0.4.3"
edition = "2024"

[dependencies]
tilekit = {path = "../tilekit"}
clap = { version = "4.5.48", features = ["derive"] }
reqwest = { version = "0.12", features = ["json", "blocking", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tokio = { version = "1" , features = ["macros", "rt-multi-thread"]}
owo-colors = "4"
futures-util = "0.3"
hf-hub = {version = "0.4", features = ["tokio"]}
rustyline = "17.0"
toml = "1.0.3"
semver = "1.0"
rusqlite = { version = "0.38.0", features = ["bundled"] }
rusqlite_migration = "2.4.1"
uuid = {version = "1.21.0", features = ["v7"]}

[dev-dependencies]
tempfile = "3"
keyring = { version = "3", features = ["apple-native"] }
wiremock = "0.6.5"
async-std = { version = "1.12", features = ["attributes"] }
